apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
 tls:
 - hosts:
   - lab.chambreuil.com
 rules:
  - host: lab.chambreuil.com
    http:
      paths:
      - path: /longpolling
        backend:
          serviceName: longpolling
          servicePort: 8072
      - path: /
        backend:
          serviceName: odoo
          servicePort: 8069
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
